services:
  init:
    image: alpine:3.22@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
    init: true
    volumes:
      - mongo-logs:/var/log-mongo
      - tempo-data:/var/tempo
    command: >
      chmod 777 /var/log-mongo && chown -R 10001:10001 /var/tempo

  app:
    container_name: license-inventory
    image: node:23-alpine@sha256:a34e14ef1df25b58258956049ab5a71ea7f0d498e41d0b514f4b8de09af09456
    # ensure colours show
    tty: true
    command: >
      sh -c "npm install --include=optional && npm run dev"
    environment:
      MONGO_URI: mongodb://mongo:27017/inventory
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: license-inventory
      OTEL_RESOURCE_ATTRIBUTES: service.version=0.0.0
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      # have a separate node dependencies
      # avoids permissions conflicts
      - node-deps:/usr/src/app/node_modules
    depends_on:
      - mongo
      - otel-collector

  mongo:
    image: mongo:8.0.11@sha256:5941949d3887e40be5175787aade07dc052f2cddb8ce21b740c3948eba6a3ed0
    command: --logpath=/var/log/mongo.log
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log
    depends_on:
      - init

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.129.1@sha256:4798e3095561ac8ae13a81965088d68b943b1991bbeede91b1564e12c95372cc
    volumes:
      - ./dev/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - loki
      - tempo

  promtail:
    image: grafana/promtail:3.5.1@sha256:65bfae480b572854180c78f7dc567a4ad2ba548b0c410e696baa1e0fa6381299
    command:
      - -config.file=/etc/promtail/config.yaml
      - -log.level=warn
    volumes:
      - ./dev/promtail.yaml:/etc/promtail/config.yaml
      - mongo-logs:/var/log-mongo
    depends_on:
      - loki

  # traces
  tempo:
    image: grafana/tempo:2.8.1@sha256:bc9245fe3da4e63dc4c6862d9c2dad9bcd8be13d0ba4f7705fa6acda4c904d0e
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=warn
    volumes:
      - ./dev/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    depends_on:
      - init
      - prometheus

  # metrics
  prometheus:
    image: prom/prometheus:v3.4.2@sha256:3b1d5be5c3eef4f027665ddaa3b1a7de8a58d96a0a6de5dd45629afd267ecaf0
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receive
      - --web.enable-otlp-receiver
      - --log.level=warn
    volumes:
      - ./dev/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090

  # logs
  loki:
    image: grafana/loki:3.5.1@sha256:a74594532eec4cc313401beedc4dd2708c43674c032084b1aeb87c14a5be1745
    command:
      - -config.file=/etc/loki/loki.yaml
      - -log.level=warn
    ports:
      - 3100:3100
    volumes:
      - ./dev/loki.yaml:/etc/loki/loki.yaml

  # everything dashboard
  grafana:
    image: grafana/grafana:12.0.2@sha256:b5b59bfc7561634c2d7b136c4543d702ebcc94a3da477f21ff26f89ffd4214fa
    ports:
      - 3001:3000
    volumes:
      - ./dev/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      # seem to get auth warnings even though we're on anonymous auth
      - GF_LOG_LEVEL=error
    depends_on:
      - loki
      - tempo
      - prometheus

volumes:
  mongo-logs:
  mongo-data:
  tempo-data:
  node-deps:
